language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
cache:
  directories:
    - dante-1.4.0
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential dnsutils iproute nginx bc
  - sudo sh -c "echo '127.0.0.1    localhost' > /etc/hosts"
  - sudo service nginx restart
  - pip install pep8 pyflakes nose coverage PySocks
script:
  - tests/jenkins.sh
